// <auto-generated />
namespace BLD_TC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class buslaneTimeTypes1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(buslaneTimeTypes1));
        
        string IMigrationMetadata.Id
        {
            get { return "201401271325490_buslaneTimeTypes1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
